ARG SOURCE_IMAGE

FROM ${SOURCE_IMAGE}
COPY --from=ccr.ccs.tencentyun.com/ags-image/envd@sha256:2fe2b8621485874d56216d898dbe8cb60ffa177691be7f8e18a7f906fcbc3851 --chmod=755 /usr/bin/envd /usr/bin/envd
